### PR TITLE
Added prettier config and changed filenames from README.md to variable

### PR DESCRIPTION
**Pull request by abhijoshi2k**
I think most of it is complete. However, we need to change the index.js file in dist folder once our root file is final.

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Looks good, one sec

**Review by PuneetGopinath — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
Wait sorry, I interrupted in this pr

**Comment by abhijoshi2k** [comment]
Can you revert your commit on branch `patch-3` and then commit again after having proper configuration of `prettier`?

**Comment by PuneetGopinath** [comment]
Ohh ok

**Comment by abhijoshi2k** [comment]
Have u created the final build in latest commit?

**Comment by PuneetGopinath** [comment]
Will do it

**Comment by PuneetGopinath** [comment]
Done by github actions now

**Comment by PuneetGopinath** [comment]
Can we create a new pr again, I have never worked with collaborators, I didn't remember to open a pr instead of directly pushing

**Comment by abhijoshi2k** [comment]
I think this branch is perfect. Only thing is that build has not been run yet!
So we can merge this pr to master and then run build on master.

**Comment by PuneetGopinath** [comment]
Ok, as you wish

**Pull request merged**
